/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert/Alert.vue')['default']
    BackTop: typeof import('./src/components/BackTop/BackTop.vue')['default']
    Basic: typeof import('./src/components/Switch/Basic.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    Code: typeof import('./src/components/Code/Code.vue')['default']
    Collapse: typeof import('./src/components/Collapse/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/Collapse/CollapseItem.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/ColorPicker.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker/DatePicker.vue')['default']
    Dialog: typeof import('./src/components/Dialog/Dialog.vue')['default']
    Divider: typeof import('./src/components/Divider/Divider.vue')['default']
    Drawer: typeof import('./src/components/Drawer/Drawer.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/Dropdown.vue')['default']
    Form: typeof import('./src/components/Form/Form.vue')['default']
    FormItem: typeof import('./src/components/Form/FormItem.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    Image: typeof import('./src/components/Image/Image.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    Links: typeof import('./src/components/Links/Links.vue')['default']
    List: typeof import('./src/components/List/List.vue')['default']
    Markdown: typeof import('./src/components/Markdown/Markdown.vue')['default']
    Messaage: typeof import('./src/components/Message/Messaage.vue')['default']
    ORcode: typeof import('./src/components/QRcode/ORcode.vue')['default']
    Point: typeof import('./src/components/Point/Point.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select/Select.vue')['default']
    Slider: typeof import('./src/components/Slider/Slider.vue')['default']
    Space: typeof import('./src/components/Space/Space.vue')['default']
    Swiper: typeof import('./src/components/Swiper/Swiper.vue')['default']
    SwiperItem: typeof import('./src/components/Swiper/Swiper-item.vue')['default']
    Switch: typeof import('./src/components/Switch/Switch.vue')['default']
    Tag: typeof import('./src/components/Tag/Tag.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip/Tooltip.vue')['default']
  }
}
